#!/usr/bin/env python3
import pathlib
import subprocess
import re

root_dir = pathlib.Path(__file__).parent.parent.parent
venv_bin = root_dir / "venv/bin"


def main():
    rvalue = subprocess.run(
        ["/usr/local/bin/git", "diff", "--name-only", "--cached"],
        stdout=subprocess.PIPE,
    )
    output = rvalue.stdout.decode("utf-8").strip()
    lines = re.split(r"\n", output)
    python_files = []
    markdown_files = []
    for line in lines:
        if re.search(r"\.py$", line) and pathlib.Path(line).exists():
            python_files.append(line)
        elif re.search(r"\.md$", line) and pathlib.Path(line).exists():
            markdown_files.append(line)

    markdownlint = subprocess.run(
        ["command", "-v", "markdownlint"],
        stdout=subprocess.PIPE,
    )
    if markdownlint:
      for file in markdown_files:
        subprocess.run(
            [markdownlint, "--fix", file],
            stdout=subprocess.PIPE,
        )

    if not len(python_files):
        print("No python files to lint - exiting")
        return
    commands = ["isort", "black", "flake8", "mypy"]
    for cmd in commands:
        print(f"running {cmd}")
        executable = str(venv_bin / cmd)
        subprocess.run([executable] + python_files)
    subprocess.run(["/usr/local/bin/git", "add"] + python_files)

    print("copying .env file")
    copy_env_path = str(root_dir / ".bin/copy-env")
    env_sample_path = root_dir / ".env.sample"
    subprocess.run([copy_env_path])
    subprocess.run(["/usr/local/bin/git", "add", str(env_sample_path)])


if __name__ == "__main__":
    main()
