#!/usr/bin/env python3
import subprocess
import re
import sys


args = sys.argv
if "--version" in args:
    value_index = args.index("--version") + 1
    version = args[value_index]

if not version:
    version = input("New version tag: ")
    if not version:
        raise Exception("Tag value is required")


def exec(command: str):
    parts = command.split(" ")
    return subprocess.check_output(parts, encoding="utf-8").strip()


sections = []
# git_tags = []
for tag in [version] + exec("git tag --list").split("\n"):
    commit = ""
    if tag and tag != version:
        commit = exec(f"git show-ref -s --abbrev=7 {tag}")
    sections.append({"tag": tag, "commit": commit, "items": []})

active_section_index = 0
# active_tag_commit = sections[0]['commit']
logs = exec("git log --format=%h__%s__%b>>").split(">>")
for line in logs:
    line = line.strip()
    if not len(line):
        continue
    [commit, title, body] = line.split("__")
    if not sections[active_section_index]["commit"]:
        sections[active_section_index]["commit"] = commit
    next_index = active_section_index + 1
    if len(sections) > next_index:
        if sections[next_index]["commit"] == commit:
            active_section_index = next_index
    body = body.replace("\n*", "    *")
    item_string = f"""- [{commit}](https://github.com/nielse63/alpaca-trading-scripts/commit/{commit}) - {title}
  {body}
  """.strip()
    item_string = (
        re.sub(
            r"\(#\d+\)",
            r"[\g<0>](https://github.com/nielse63/alpaca-trading-scripts/pull/\g<0>)",
            item_string,
        )
        .replace("pull/(#", "pull/")
        .replace("))", ")")
    )
    sections[active_section_index]["items"].append(item_string)

template_lines = ["# Changelog"]
for section in sections:
    if not len(section["items"]):
        continue
    template_lines += ["", f"## {section['tag']}", "", *section["items"], ""]
template = "\n".join(template_lines)

# write to markdown file
file = open("CHANGELOG.md", "w")
file.write(template)
