#!/usr/bin/env node
const fs = require('fs-extra');
const path = require('path');
const cp = require('child_process');

const exec = (cmd) => {
  return new Promise((resolve, reject) => {
    cp.exec(cmd, (error, stdout, stderr) => {
      if (error) {
        return reject(new Error(stderr));
      }
      resolve(stdout);
    });
  });
};

const copyEnv = async () => {
  const envfile = path.resolve(__dirname, '../.env');
  const samplefile = path.resolve(__dirname, '../.env.sample');

  if (!fs.existsSync(envfile)) {
    console.warn('.env file not found - exiting');
    process.exit();
  }

  const oldContent = await fs.readFile(samplefile, 'utf-8');
  const content = await fs.readFile(envfile, 'utf-8');
  const lines = content.split('\n');
  const newLines = lines
    .filter((line) => {
      return !!line.trim() && !line.startsWith('#');
    })
    .map((line) => {
      const [key, value] = line.split('=');
      let newValue = value;
      if (/"|'/.test(value)) {
        newValue = '""';
      } else {
        newValue = '';
      }
      return `${key.trim()}=${newValue.trim()}`;
    });
  const newContent = newLines.join('\n');
  if (oldContent !== newContent) {
    await fs.writeFile(samplefile, newContent);
    await exec('git add .env.sample');
    console.log('updated .env.sample');
  }
};

copyEnv().catch(console.error);
