#!/usr/bin/env node
const fs = require('fs-extra');
const path = require('path');

const copyEnv = async () => {
  const envfile = path.resolve(__dirname, '../.env');
  const samplefile = path.resolve(__dirname, '../.env.sample');

  if (!fs.existsSync(envfile)) {
    console.warn('.env file not found - exiting');
    process.exit();
  }

  const content = await fs.readFile(envfile, 'utf-8');
  const lines = content.split('\n');
  const newLines = lines
    .filter((line) => {
      return !!line.trim() && !line.startsWith('#');
    })
    .map((line) => {
      const [key, value] = line.split('=');
      let newValue = value;
      if (/"|'/.test(value)) {
        newValue = '""';
      } else {
        newValue = '';
      }
      return `${key.trim()}=${newValue.trim()}`;
    });
  const sampleContent = newLines.join('\n');
  await fs.writeFile(samplefile, sampleContent);
  console.log('updated .env.sample');
};

copyEnv().catch(console.error);
