#!/usr/bin/env bash
set -e

staged_files=$(git diff --stat)
if [ "$staged_files" ]; then
  echo "Commit all changes before continuing with release"
  exit
fi

git checkout main
git pull

read new_version

# update the changelog
.bin/changelog --version $new_version

npx markdownlint CHANGELOG.md
git add CHANGELOG.md
git commit -m 'chore: updating changelog before release'
git push
/usr/local/bin/gh release create $new_version \
  --title $new_version \
  --notes '' \
  --target 'main'
