#!/usr/bin/env bash
set -e

SHOW_LOGS=false

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  --logs )
    SHOW_LOGS=true
    ;;
esac; shift; done
if [[ "$1" == '--' ]]; then shift; fi

echo "Restarting..."

root="$(dirname "$(dirname "$(realpath "$0")")")"
cd "$root"

pm2 stop all
npm run build
pm2 start all
if [ $SHOW_LOGS = true ]; then
  pm2 logs --lines 30
fi
