#!/usr/bin/env bash
set -e

rm -f "/tmp/local.alpaca.*"

root=$(dirname "$(dirname "$0")")
if ! [ -d "$root" ]; then
  echo "value of \$root is not a directory - exiting"
  exit 1
fi

cd "$root"

if ! [ -d "$root/node_modules" ]; then
  npm ci
fi
npm run build

node dist/index.js
