#!/usr/bin/env bash
set -e

echo "Cleaning old files"
.bin/clean

echo "Setting up environment"
python3.9 -m venv venv
if [ ! -f "activate" ]; then
  ln -s venv/bin/activate activate
fi
. activate
python -m pip install --upgrade pip
pip install -r requirements.txt
python setup.py develop
