#!/usr/bin/env bash
set -e

python3.9 -m venv venv
if [ ! -f "activate" ]; then
  ln -s venv/bin/activate activate
fi
. activate
python -m pip install --upgrade pip
pip install -r requirements.txt
python setup.py develop
