#!/usr/bin/env bash
set -e

python3.9 -m venv venv
if [ ! -f "activate" ]; then
  ln -s venv/bin/activate activate
fi
if [ -f "trading_scripts/__init__.py" ]; then
  rm trading_scripts/__init__.py
fi
. activate
python -m pip install --upgrade pip
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -r requirements-test.txt
python setup.py develop

# install git hooks
if [ ! "$CI" ]; then
  if [ -d  ".git" ]; then
    for f in .bin/hooks/*; do
      cp -v $f ".git/hooks/$(basename $f)"
    done
  fi
fi
