#!/usr/bin/env bash
set -e

. activate
venv/bin/isort trading_scripts ./*.py
venv/bin/black trading_scripts ./*.py
venv/bin/flake8 trading_scripts ./*.py
venv/bin/mypy trading_scripts ./*.py

# find extra dependencies that aren't needed
# pip-extra-reqs --ignore-requirement=tabulate trading_scripts/

# find dead code
# vulture --min-confidence=0 trading_scripts main.py
