#!/usr/bin/env bash
set -e

. activate
isort trading_scripts ./*.py
black trading_scripts ./*.py
flake8 trading_scripts ./*.py
mypy trading_scripts ./*.py

# find extra dependencies that aren't needed
pip-extra-reqs trading_scripts/

# find dead code
vulture --min-confidence=0 trading_scripts main.py
